/* eslint-disable @typescript-eslint/no-unnecessary-template-expression */
import type { Events } from 'events-constructor';

export enum EEvent {
  CHANNELS_NOTIFY = 'channels:notify',
  PARTICIPANT_ADDED_TO_LIST_MODERATORS = 'participant:added-to-list-moderators',
  PARTICIPANT_REMOVED_FROM_LIST_MODERATORS = 'participant:removed-from-list-moderators',
  PARTICIPANT_MOVE_REQUEST_TO_STREAM = 'participant:move-request-to-stream',
  PARTICIPANT_MOVE_REQUEST_TO_SPECTATORS = 'participant:move-request-to-spectators',
  PARTICIPANT_MOVE_REQUEST_TO_PARTICIPANTS = 'participant:move-request-to-participants',
  PARTICIPATION_ACCEPTING_WORD_REQUEST = 'participation:accepting-word-request',
  PARTICIPATION_CANCELLING_WORD_REQUEST = 'participation:cancelling-word-request',
  WEBCAST_STARTED = 'webcast:started',
  WEBCAST_STOPPED = 'webcast:stopped',
  ACCOUNT_CHANGED = 'account:changed',
  ACCOUNT_DELETED = 'account:deleted',
  CONFERENCE_PARTICIPANT_TOKEN_ISSUED = 'conference:participant-token-issued',
  CHANNELS = 'channels',
  ENTER_ROOM = 'enterRoom',
  SHARE_STATE = 'shareState',
  MAIN_CAM_CONTROL = 'main-cam-control',
  USE_LICENSE = 'useLicense',
  ADMIN_START_MAIN_CAM = 'admin-start-main-cam',
  ADMIN_STOP_MAIN_CAM = 'admin-stop-main-cam',
  ADMIN_START_MIC = 'admin-start-mic',
  ADMIN_STOP_MIC = 'admin-stop-mic',
  ADMIN_FORCE_SYNC_MEDIA_STATE = 'admin-force-sync-media-state',
  AVAILABLE_SECOND_REMOTE_STREAM = 'availableSecondRemoteStream',
  NOT_AVAILABLE_SECOND_REMOTE_STREAM = 'notAvailableSecondRemoteStream',
  MUST_STOP_PRESENTATION = 'mustStopPresentation',
  NEW_DTMF = 'newDTMF',
  RESTART = 'restart',
}

export const EVENT_NAMES = [
  `${EEvent.PARTICIPATION_ACCEPTING_WORD_REQUEST}`,
  `${EEvent.PARTICIPATION_CANCELLING_WORD_REQUEST}`,
  `${EEvent.PARTICIPANT_MOVE_REQUEST_TO_STREAM}`,
  `${EEvent.CHANNELS_NOTIFY}`,
  `${EEvent.CONFERENCE_PARTICIPANT_TOKEN_ISSUED}`,
  `${EEvent.ACCOUNT_CHANGED}`,
  `${EEvent.ACCOUNT_DELETED}`,
  `${EEvent.WEBCAST_STARTED}`,
  `${EEvent.WEBCAST_STOPPED}`,
  `${EEvent.PARTICIPANT_ADDED_TO_LIST_MODERATORS}`,
  `${EEvent.PARTICIPANT_REMOVED_FROM_LIST_MODERATORS}`,
  `${EEvent.PARTICIPANT_MOVE_REQUEST_TO_SPECTATORS}`,
  `${EEvent.PARTICIPANT_MOVE_REQUEST_TO_PARTICIPANTS}`,
  `${EEvent.CHANNELS}`,
  `${EEvent.ENTER_ROOM}`,
  `${EEvent.SHARE_STATE}`,
  `${EEvent.MAIN_CAM_CONTROL}`,
  `${EEvent.USE_LICENSE}`,
  `${EEvent.ADMIN_START_MAIN_CAM}`,
  `${EEvent.ADMIN_STOP_MAIN_CAM}`,
  `${EEvent.ADMIN_START_MIC}`,
  `${EEvent.ADMIN_STOP_MIC}`,
  `${EEvent.ADMIN_FORCE_SYNC_MEDIA_STATE}`,
  `${EEvent.AVAILABLE_SECOND_REMOTE_STREAM}`,
  `${EEvent.NOT_AVAILABLE_SECOND_REMOTE_STREAM}`,
  `${EEvent.MUST_STOP_PRESENTATION}`,
  `${EEvent.NEW_DTMF}`,
  `${EEvent.RESTART}`,
] as const;

export type TEvent = (typeof EVENT_NAMES)[number];
export type TEvents = Events<typeof EVENT_NAMES>;
