export const DISCONNECT_CAUSE_HEADER = 'X-VINTEO-DISCONNECT-CAUSE';

export enum EDisconnectCause {
  INSUFFICIENT_LICENSES = 'INSUFFICIENT_LICENSES',
  P2P_NO_ANSWER = 'P2P_NO_ANSWER',
  ROOM_CONNECTION_LIMIT = 'ROOM_CONNECTION_LIMIT',
  DISCONNECTED_BY_MODERATOR = 'DISCONNECTED_BY_MODERATOR',
  CONFERENCE_FINISHED = 'CONFERENCE_FINISHED',
  P2P_REMOTE_UNAVAILABLE = 'P2P_REMOTE_UNAVAILABLE',
  MODERATOR_LEFT = 'MODERATOR_LEFT',
  ANONYMOUS_CONNECTION_FORBIDDEN = 'ANONYMOUS_CONNECTION_FORBIDDEN',
  MODERATOR_REQUIRED = 'MODERATOR_REQUIRED',
}

export const DISCONNECT_CAUSES: Partial<Record<number, EDisconnectCause>> = {
  1000: EDisconnectCause.INSUFFICIENT_LICENSES,
  1001: EDisconnectCause.P2P_NO_ANSWER,
  1002: EDisconnectCause.ROOM_CONNECTION_LIMIT,
  1003: EDisconnectCause.DISCONNECTED_BY_MODERATOR,
  1004: EDisconnectCause.CONFERENCE_FINISHED,
  1006: EDisconnectCause.P2P_REMOTE_UNAVAILABLE,
  1007: EDisconnectCause.MODERATOR_LEFT,
  1008: EDisconnectCause.ANONYMOUS_CONNECTION_FORBIDDEN,
  1009: EDisconnectCause.MODERATOR_REQUIRED,
};
